// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SolicitudesGastos.Infrastructure.Persistence;

#nullable disable

namespace SolicitudesGastos.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260331024019_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SolicitudesGastos.Domain.Entities.SolicitudGasto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FechaDecision")
                        .HasColumnType("datetime2");

                    b.Property<string>("Usuario")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("SolicitudesGastos", (string)null);
                });

            modelBuilder.Entity("SolicitudesGastos.Domain.Entities.SolicitudGasto", b =>
                {
                    b.OwnsOne("SolicitudesGastos.Domain.ValueObjects.FechaGasto", "FechaGasto", b1 =>
                        {
                            b1.Property<int>("SolicitudGastoId")
                                .HasColumnType("int");

                            b1.Property<DateTime>("Value")
                                .HasColumnType("datetime2")
                                .HasColumnName("FechaGasto");

                            b1.HasKey("SolicitudGastoId");

                            b1.ToTable("SolicitudesGastos");

                            b1.WithOwner()
                                .HasForeignKey("SolicitudGastoId");
                        });

                    b.OwnsOne("SolicitudesGastos.Domain.ValueObjects.ValorGasto", "Valor", b1 =>
                        {
                            b1.Property<int>("SolicitudGastoId")
                                .HasColumnType("int");

                            b1.Property<decimal>("Value")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("Valor");

                            b1.HasKey("SolicitudGastoId");

                            b1.ToTable("SolicitudesGastos");

                            b1.WithOwner()
                                .HasForeignKey("SolicitudGastoId");
                        });

                    b.Navigation("FechaGasto")
                        .IsRequired();

                    b.Navigation("Valor")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
