name: CI - Tests

on:
  push:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    # =========================
    # FRONTEND
    # =========================
    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: 20

    - name: Install frontend
      working-directory: frontend/solicitudes-gastos
      run: npm install

    - name: Run frontend tests
      working-directory: frontend/solicitudes-gastos
      run: npm run test -- --watch=false

    # =========================
    # BACKEND
    # =========================
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore backend
      working-directory: backend/SolicitudesGastos
      run: dotnet restore

    - name: Build backend
      working-directory: backend/SolicitudesGastos
      run: dotnet build --no-restore

    - name: Test backend
      working-directory: backend/SolicitudesGastos
      run: dotnet test --no-build --verbosity normal